import FWCore.ParameterSet.Config as cms

MTD4DVertexingAnalyzer = cms.EDAnalyzer('MTD4DVertexingAnalyzer',
                                        genParticlesTag = cms.untracked.InputTag("genParticles"),
                                        trackingParticlesTag = cms.untracked.InputTag("mix", "MergedTrackTruth"),
                                        trackAndTrackingParticlesAssociatorMapTag = cms.untracked.InputTag("trackingParticleRecoTrackAsssociation"),
                                        generalTracksTag = cms.untracked.InputTag("generalTracks"),
                                        extendedTracksTag = cms.untracked.InputTag("trackExtenderWithMTD", ""),
                                        generalToExtendedTrkMapTag = cms.untracked.InputTag("trackExtenderWithMTD", "generalTrackassoc"),
                                        btlMatchChi2Tag = cms.untracked.InputTag("trackExtenderWithMTD", "btlMatchChi2"),
                                        btlMatchTimeChi2Tag = cms.untracked.InputTag("trackExtenderWithMTD", "btlMatchTimeChi2"),
                                        etlMatchChi2Tag = cms.untracked.InputTag("trackExtenderWithMTD", "etlMatchChi2"),
                                        etlMatchTimeChi2Tag = cms.untracked.InputTag("trackExtenderWithMTD", "etlMatchTimeChi2"),
                                        extTracksPathLengthTag = cms.untracked.InputTag("trackExtenderWithMTD", "pathLength"),
                                        extTracksMTDtimeTag = cms.untracked.InputTag("trackExtenderWithMTD", "tmtd"),
                                        t0TOFPIDTag = cms.untracked.InputTag("tofPID", "t0"),
                                        sigmat0TOFPIDTag = cms.untracked.InputTag("tofPID", "sigmat0"),
                                        probPiTOFPIDTag = cms.untracked.InputTag("tofPID", "probPi"),
                                        probPTOFPIDTag = cms.untracked.InputTag("tofPID", "probP"),
                                        probKTOFPIDTag = cms.untracked.InputTag("tofPID", "probK"),
                                        genXYZTag = cms.untracked.InputTag("genParticles", "xyz0", "HLT"),
                                        genT0Tag = cms.untracked.InputTag("genParticles", "t0", "HLT"),
                                        simVtxTag = cms.untracked.InputTag("mix", "InitialVertices", "HLT"),
                                        vtx3DTag = cms.untracked.InputTag("offlinePrimaryVertices", "", "RECO"),
                                        vtx4DTag = cms.untracked.InputTag("offlinePrimaryVertices4D", ""),
                                        vtx4DNoPIDTag = cms.untracked.InputTag("offlinePrimaryVertices4DnoPID", ""),                                        
                                        trackPUID_3DBDT_weights_file = cms.FileInPath("PrecisionTiming/FTLAnalysis/data/bo_optimized_clf3D_PMV13_v1.xml"),
                                        #trackPUID_4DBDT_weights_file = cms.FileInPath("PrecisionTiming/FTLAnalysis/data/bo_optimized_clf4D_PMV13_v1.xml"),
                                        trackPUID_4DBDT_weights_file = cms.FileInPath("PrecisionTiming/FTLAnalysis/data/bo_optimized_clf4D_PMV13_MTDquality_v1.xml"),
                                        vtxsTreeName = cms.untracked.string("vtxs_tree"),
                                        trksTreeName = cms.untracked.string("trks_tree")
)
